#version: "3.9"

services:
  backend:
    build: ./BC-backend
    container_name: BC-flask-backend
    ports:
      - "5000:5000"
    networks:
      - app-network

  frontend:
    build: ./BC-frontend
    container_name: BC-react-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    develop:
      watch:
        - path: ./BC-frontend/src
          action: sync
          target: /app/src

networks:
  app-network:
    driver: bridge