# ---- Stage 1: Build the React app ----
FROM node:20-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the app
COPY . .

# use port 3000 and run dev mode
EXPOSE 3000
CMD ["npm", "run", "dev"]




# ---------------------------------------
# Save this part for production I suppose
# ---------------------------------------

# # Build the app for production
# RUN npm run build

# ---- Stage 2: Serve with Nginx ----
# FROM nginx:alpine

# # Copy built files to Nginx
# COPY --from=builder /app/dist /usr/share/nginx/html

# # Expose port 80
# EXPOSE 80

# # Start Nginx
# CMD ["nginx", "-g", "daemon off;"]
